[workspace]
members = ["crates/*"]
resolver = "2"

[patch.crates-io]
transmission-rpc-client = { path = "crates/transmission-rpc-client" }

[profile.release]
strip = "symbols"
opt-level = "s"
panic = "abort"
